### PR TITLE
feat: speed up objects loops

### PR DESCRIPTION
**Pull request by simone-sanfratello**
iterate object with `Object.keys` and a for loop on keys is faster than iterate using `for in`

https://github.com/simone-sanfratello/node-bench-iteration

https://simone-sanfratello.github.io/public/node-bench-iteration/index.html

### CODE REVIEW

**Review by AsyncBanana — APPROVED** [review]
LGTM

**Comment by AsyncBanana** [comment]
Thanks for the PR!
Because of the added size, I decided not to merge this for now. However, if you have any ideas for reducing the size while keeping the speed advantage of this, I would be happy to look at this again.

**Comment by simone-sanfratello** [comment]
if size is very important, I recommend to use `uglify` on the `build` script

```
uglifyjs dist/index.js -c -m > dist/index-compres.js
```

**Comment by AsyncBanana** [comment]
I was considering that when I started the project, but I was more focused on size for web projects, as this project is for both the web and Node. Most people using it on the web will probably use minifiers themselves, and many people using Node like seeing the code in their dependencies directly.
I started #8 to see the community's opinions on this. You can add your own opinion if you want.

**Comment by danialdezfouli** [comment]
using `Array.length` in for loops has a performance cost; you can save it before the loop, like this:
const keysLength = keys.length;

**Comment by AsyncBanana** [comment]
I am closing this because I will not implement this unless something changes my mind.

**Pull request closed without merging**
