### PR TITLE
Add old value to changing difference

### PR DESCRIPTION
**Pull request by denis-bel**
Hello, for my project I really need to get old values when object have been changed (updated). It's long enough and inefficient to take old value from path. I think it will be great if you add old value from old object to difference when there are changes. Thank you!

### CODE REVIEW

**Comment by AsyncBanana** [comment]
Thanks for the PR! Two things:
First, I think the old value could be added to the `REMOVE` type, like how the new value is in the `CREATE` type.
Second, it would be helpful to add to the docs to reflect this in the PR. However, I can do that myself if you do not want to.
Other than that, it looks good!

**Comment by denis-bel** [comment]
Yes, adding old value to REMOVE type is awesome idea. Can you please add it, and update docs, because i don't know how to update this pull request to add removed value?

> Thanks for the PR! Two things: First, I think the old value could be added to the `REMOVE` type, like how the new value is in the `CREATE` type. Second, it would be helpful to add to the docs to reflect this in the PR. However, I can do that myself if you do not want to. Other than that, it looks good!

**Comment by denis-bel** [comment]
I added old value in REMOVE type and also I updated docs. Check please the changes. Thank you!

**Comment by AsyncBanana** [comment]
Sorry for all of the complications. I want to make sure there are not any problems later. First, I think `deletedValue` and `oldValue` should be merged, since `oldValue` covers `deletedValue`, and it could cause some confusion for which to use (also look at how `CREATE` just uses `value`, not `newValue`).
Second, it would be helpful to update the testing to use this, although I could do it myself.
These should be the last things needed.

**Comment by denis-bel** [comment]
Can you please do it yourself? I think it would be the best option ;)

**Comment by AsyncBanana** [comment]
Ok, I will. Thanks again for the PR.

**Pull request merged**
